name: model-training
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}

        run: |
          pip install -r requirements.txt
          dvc pull data/AdSmartABdata.csv --run-cache

          python -m train.decision_trees.py
          cat train/metrics.txt >> report.md


          # # Report metrics
          # echo "## Metrics" >> report.md
          # git fetch --prune
          # dvc metrics diff master --show-md >> report.md

          # cat metrics.txt >> report.md
          cml-publish train/confusion_matrix.png --md >> report.md
          cml-send-comment report.md
