name: model-training
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}

        run: |
          pip install -r requirements.txt
          # dvc pull data --run-cache
          dvc pull data/AdSmartABdata.csv --run-cache
          cd train
          python decision_trees.py
          echo "## Decision Tree Metrics" >> report.md  
          cat dt_metrics.txt >> report.md
          cml-publish dt_confusion_matrix.png --md >> report.md

          python xgb.py
          echo "## XGBClassifier Metrics" >> report.md  
          cat xgb_metrics.txt >> report.md
          cml-publish xgb_confusion_matrix.png --md >> report.md

          python logistic_regression.py
          echo "## Logistic Regression Metrics" >> report.md  
          cat lr_metrics.txt >> report.md
          cml-publish lr_confusion_matrix.png --md >> report.md


          cml-send-comment report.md
